version: '3.1'

services:
  web:
    image: epandurski/cmbarter:1.15-web
    build:
      context: .
      dockerfile: docker/Dockerfile-web
    depends_on:
      - db
    volumes:
      - sessions-volume:/var/tmp/cmbarter
    env_file: docker-compose.config
      
  db:
    image: epandurski/cmbarter:1-db
    build:
      context: .
      dockerfile: docker/Dockerfile-db
    volumes:
      - data-volume:/var/lib/postgresql/data
      
  mail:
    image: epandurski/cmbarter:mail
    build:
      context: .
      dockerfile: docker/Dockerfile-mail
    volumes:
      - mailqueue-volume:/var/spool/exim4

  tasks:
    image: epandurski/cmbarter:1.15-tasks
    build:
      context: .
      dockerfile: docker/Dockerfile-tasks
    depends_on:
      - db
      - mail
    volumes:
      - sessions-volume:/var/tmp/cmbarter
    env_file: docker-compose.config

  proxy:
    image: epandurski/cmbarter:proxy
    build:
      context: .
      dockerfile: docker/Dockerfile-proxy
    secrets:
      - source: ssl_certificate
        target: cert.pem
      - source: ssl_certificate_key
        target: key.pem
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"


volumes:
  data-volume:
  sessions-volume:
  mailqueue-volume:


secrets:
  ssl_certificate:
    file: ./cert.pem
  ssl_certificate_key:
    file: ./key.pem