version: '3'

services:
  web:
    image: epandurski/cmbarter:1.15-web
    build:
      context: .
      dockerfile: docker/Dockerfile-web
    depends_on:
      - db
      - tasks
    environment:
      # Set this to the number of worker processes for handling requests --
      # a positive integer generally in the 2-4 * $NUM_CORES range. You may
      # want to vary this a bit to find the best for your particular
      # workload.
      WEB_CONCURRENCY: 1
      
      # Set this to your site domain name.
      CMBARTER_HOST: 'localhost'
      
      # Make this long and unique, and don't share it with anybody.
      CMBARTER_SECRET_KEY: 'your secret key'
      
      # By default, CMB is configured to show CAPTHCA on sign-up, and after
      # five unsuccessful attempts to log-in. If you have not altered the
      # default behavior, you should obtain your own public/private key pair
      # from www.google.com/recaptcha, and put it here:
      CMBARTER_RECAPTCHA_PUBLIC_KEY: '6Ledx7wSAAAAAICFw8vB-2ghpDjzGogPRi6-3FCr'
      CMBARTER_RECAPTCHA_PIVATE_KEY: '6Ledx7wSAAAAAEskQ7Mbi-oqneHDSFVUkxGitn_y'
      
      # This should point to a page telling more about the site.
      CMBARTER_ABOUT_US_URL: 'https://sourceforge.net/projects/cmb/'

  db:
    image: epandurski/cmbarter:1-db
    build:
      context: .
      dockerfile: docker/Dockerfile-db
    volumes:
      - data-volume:/var/lib/postgresql/data
    deploy:
      mode: global
      
  mail:
    image: epandurski/cmbarter:mail
    build:
      context: .
      dockerfile: docker/Dockerfile-mail
    volumes:
      - mailqueue-volume:/var/spool/exim4

  tasks:
    image: epandurski/cmbarter:1.15-tasks
    build:
      context: .
      dockerfile: docker/Dockerfile-tasks
    depends_on:
      - db
      - mail
    environment:
      # Set this to your site domain name.
      CMBARTER_HOST: 'localhost'

  proxy:
    # This image uses a self-signed SSL certificate. You will need to
    # overwrite /etc/nginx/ssl/cert.pem and /etc/nginx/ssl/key.pem
    # with a proper certificate and a private key. Then create an
    # updated image.
    
    image: epandurski/cmbarter:proxy
    build:
      context: .
      dockerfile: docker/Dockerfile-proxy
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    environment:
      # Set this to your site domain name.
      CMBARTER_HOST: 'localhost'


volumes:
  # This volume will contain the PostgreSQL database.
  data-volume:
  
  # This volume will contain the outgoing mail queue.
  mailqueue-volume:
