version: '3'

services:
  web:
    image: epandurski/cmbarter:1.16-web
    build:
      context: .
      dockerfile: docker/Dockerfile-web
    depends_on:
      - db
      - tasks
    env_file: .env

  db:
    image: epandurski/cmbarter:1-db
    build:
      context: .
      dockerfile: docker/Dockerfile-db
    volumes:
      - data-volume:/var/lib/postgresql/data
    deploy:
      mode: global
      
  mail:
    image: epandurski/cmbarter:mail
    build:
      context: .
      dockerfile: docker/Dockerfile-mail
    volumes:
      - mailqueue-volume:/var/spool/exim4

  tasks:
    image: epandurski/cmbarter:1.16-tasks
    build:
      context: .
      dockerfile: docker/Dockerfile-tasks
    depends_on:
      - db
      - mail
    environment:
      CMBARTER_HOST: ${CMBARTER_HOST}
      CMBARTER_DSN: ${CMBARTER_DSN}
      CMBARTER_SECRET_KEY: ${CMBARTER_SECRET_KEY}
      CMBARTER_REGISTRATION_KEY_PREFIX: ${CMBARTER_REGISTRATION_KEY_PREFIX}

  proxy:
    # This image uses a self-signed SSL certificate. You will need to
    # overwrite /etc/nginx/ssl/cert.pem and /etc/nginx/ssl/key.pem
    # with a proper certificate and a private key. Then create an
    # updated image.
    
    image: epandurski/cmbarter:1.16-proxy
    build:
      context: .
      dockerfile: docker/Dockerfile-proxy
    depends_on:
      - web
    environment:
      CMBARTER_HOST: ${CMBARTER_HOST}
    ports:
      - "80:80"
      - "443:443"


volumes:
  # This volume will contain the PostgreSQL database.
  data-volume:
  
  # This volume will contain the outgoing mail queue.
  mailqueue-volume:
