version: '3'

services:
  web:
    image: epandurski/cmbarter:1.15-web
    build:
      context: .
      dockerfile: docker/Dockerfile-web
    networks:
      internal:
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - sessions-volume:/var/tmp/cmbarter
    environment:
      CMBARTER_DSN: 'host=db dbname=cmbarter user=postgres password=mysecretpassword'
    env_file: docker-compose.config
      
  db:
    image: epandurski/cmbarter:1-db
    build:
      context: .
      dockerfile: docker/Dockerfile-db
    networks:
      internal:
    volumes:
      - data-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 'mysecretpassword'
    deploy:
      mode: global
      
  mail:
    image: epandurski/cmbarter:mail
    build:
      context: .
      dockerfile: docker/Dockerfile-mail
    networks:
      internal:
    volumes:
      - mailqueue-volume:/var/spool/exim4
    deploy:
      mode: global

  tasks:
    image: epandurski/cmbarter:1.15-tasks
    build:
      context: .
      dockerfile: docker/Dockerfile-tasks
    networks:
      internal:
    depends_on:
      - db
      - mail
    volumes:
      - sessions-volume:/var/tmp/cmbarter
    environment:
      CMBARTER_DSN: 'host=db dbname=cmbarter user=postgres password=mysecretpassword'
    env_file: docker-compose.config

  proxy:
    build:
      context: .
      dockerfile: docker/Dockerfile-proxy
    networks:
      internal:
      external:
    depends_on:
      - web
    ports:
      - "80:80"


volumes:
  data-volume:
  sessions-volume:
  mailqueue-volume:


networks:
  internal:
  external: