version: '3.1'

services:
  web:
    image: epandurski/cmbarter:1.16.0-web
    build:
      context: .
      dockerfile: docker/Dockerfile-web
    depends_on:
      - db
      - tasks
    secrets:
      - source: secret_key
        target: CMBARTER_SECRET_KEY
      - source: registration_secret
        target: CMBARTER_REGISTRATION_SECRET
    env_file: .env

  db:
    image: epandurski/cmbarter:1-db
    build:
      context: .
      dockerfile: docker/Dockerfile-db
    volumes:
      - data-volume:/var/lib/postgresql/data
    deploy:
      mode: global
      
  tasks:
    image: epandurski/cmbarter:1.16.0-tasks
    build:
      context: .
      dockerfile: docker/Dockerfile-tasks
    depends_on:
      - db
    environment:
      CMBARTER_HOST: ${CMBARTER_HOST}
      CMBARTER_DSN: ${CMBARTER_DSN}

  proxy:
    # This image tries to find an SSL certificate and a private key at
    # /run/secrets/cert.pem and /run/secrets/key.pem.  If they are not
    # found there, it falls back to a self-signed certificate.
    
    image: epandurski/cmbarter:1.16.0-proxy
    build:
      context: .
      dockerfile: docker/Dockerfile-proxy
    depends_on:
      - web
    secrets:
      - source: ssl_cert
        target: cert.pem
      - source: ssl_key
        target: key.pem
    environment:
      CMBARTER_HOST: ${CMBARTER_HOST}
    ports:
      - "80:80"
      - "443:443"


volumes:
  data-volume:


secrets:
  ssl_cert:
    file: ./docker/cert.pem
  ssl_key:
    file: ./docker/key.pem
  secret_key:
    file: ./LICENSE
  registration_secret:
    external: true
