version: '3'

services:
  web:
    image: epandurski/cmbarter:1.15-web
    build:
      context: .
      dockerfile: docker/Dockerfile-web
    depends_on:
      - db
      - tasks
    environment:
      WEB_CONCURRENCY: 1
      CMBARTER_HOST: 'localhost'
      CMBARTER_SECRET_KEY: 'your secret key'
      CMBARTER_RECAPTCHA_PUBLIC_KEY: '6Ledx7wSAAAAAICFw8vB-2ghpDjzGogPRi6-3FCr'
      CMBARTER_RECAPTCHA_PIVATE_KEY: '6Ledx7wSAAAAAEskQ7Mbi-oqneHDSFVUkxGitn_y'
      CMBARTER_ABOUT_US_URL: 'https://sourceforge.net/projects/cmb/'

  db:
    image: epandurski/cmbarter:1-db
    build:
      context: .
      dockerfile: docker/Dockerfile-db
    volumes:
      - data-volume:/var/lib/postgresql/data
    deploy:
      mode: global
      
  mail:
    image: epandurski/cmbarter:mail
    build:
      context: .
      dockerfile: docker/Dockerfile-mail
    volumes:
      - mailqueue-volume:/var/spool/exim4

  tasks:
    image: epandurski/cmbarter:1.15-tasks
    build:
      context: .
      dockerfile: docker/Dockerfile-tasks
    depends_on:
      - db
      - mail
    environment:
      CMBARTER_HOST: 'localhost'

  proxy:
    image: epandurski/cmbarter:proxy
    build:
      context: .
      dockerfile: docker/Dockerfile-proxy
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    environment:
      CMBARTER_HOST: 'localhost'


volumes:
  data-volume:
  mailqueue-volume:
