version: '3'

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile-web
    networks:
      internal:
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - sessions-volume:/var/tmp/cmbarter
    environment:
      CMBARTER_DSN: 'host=db dbname=cmbarter user=postgres password=mysecretpassword'
    env_file: config.env
    deploy:
      mode: replicated
      replicas: 1
      
  db:
    build:
      context: ..
      dockerfile: docker/Dockerfile-db
    networks:
      internal:
    volumes:
      - data-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 'mysecretpassword'
    deploy:
      mode: global
      
  mail:
    build:
      context: ..
      dockerfile: docker/Dockerfile-mail
    networks:
      internal:
    volumes:
      - mailqueue-volume:/var/spool/exim4
    stop_signal: SIGKILL
    deploy:
      mode: global

  tasks:
    build:
      context: ..
      dockerfile: docker/Dockerfile-tasks
    networks:
      internal:
    depends_on:
      - db
      - mail
    volumes:
      - sessions-volume:/var/tmp/cmbarter
    environment:
      CMBARTER_DSN: 'host=db dbname=cmbarter user=postgres password=mysecretpassword'
    env_file: config.env
    stop_signal: SIGINT
    deploy:
      mode: global


volumes:
  data-volume:
  sessions-volume:
  mailqueue-volume:


networks:
  internal:
