version: '3'

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile-web
    depends_on:
      - db
    links:
      - db
    ports:
      - "8000:8000"
    volumes:
      - sessions-volume:/var/tmp/cmbarter
    environment:
      CMBARTER_DSN: 'host=db user=postgres password=mysecretpassword'
    env_file: config.env

  db:
    build:
      context: ..
      dockerfile: docker/Dockerfile-db
    volumes:
      - data-volume:/var/lib/postgresql/data

  mail:
    build:
      context: ..
      dockerfile: docker/Dockerfile-mail
    volumes:
      - mailqueue-volume:/var/spool/exim4

  tasks:
    build:
      context: ..
      dockerfile: docker/Dockerfile-tasks
    depends_on:
      - db
      - mail
    links:
      - db
      - mail
    volumes:
      - sessions-volume:/var/tmp/cmbarter
    environment:
      CMBARTER_DSN: 'host=db user=postgres password=mysecretpassword'
    env_file: config.env


volumes:
  data-volume:
  sessions-volume:
  mailqueue-volume:
